### PR TITLE
feat: added imported models from unity store

### LINKED ISSUE #20: Fox Model

### PR DESCRIPTION
**Pull request by faizazaza**

### CODE REVIEW

**Comment by hazalDK** [comment]
DISGUSTING WHAT IS THIS

**Comment by nbal21388** [comment]
WHAT DID YOU DO

**Comment by faizazaza** [comment]
PLS BE NICE

**Comment by hazalDK** [comment]
never

**Comment by quytra25** [comment]
let me contribute in this discussionnnnn, i feel left out :( what's going on

**Pull request merged**
